name: open_course
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  firebase_auth: ^4.6.1
  firebase_core: ^2.12.0
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.3
  flutter_svg: ^2.0.5
  google_fonts: ^5.0.0
  percent_indicator: ^4.2.3
  pointer_interceptor: ^0.9.3+4
  syncfusion_flutter_charts: ^21.2.4
  youtube_player_iframe: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:     
  - lib/assets/images/
