// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAowEimOVgVh0dbVLV1ZqoyBZAkxh81lAc',
    appId: '1:691177676500:web:826ea1c53b45c92a7ba541',
    messagingSenderId: '691177676500',
    projectId: 'open-course-tech',
    authDomain: 'open-course-tech.firebaseapp.com',
    storageBucket: 'open-course-tech.appspot.com',
    measurementId: 'G-WBZ1VGNFCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0cC4Dz-IHRAxF15Ih29KcRNdEoBi3yWs',
    appId: '1:691177676500:android:eb3e86e1f1cf62347ba541',
    messagingSenderId: '691177676500',
    projectId: 'open-course-tech',
    storageBucket: 'open-course-tech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFV-9cATsnyPa_oBk-5w7BmB7hm6Hk4aQ',
    appId: '1:691177676500:ios:aa30809251b86d9d7ba541',
    messagingSenderId: '691177676500',
    projectId: 'open-course-tech',
    storageBucket: 'open-course-tech.appspot.com',
    iosClientId: '691177676500-8bk8v02q7mqrfu9eqi2ekq2vrnlg1nk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.openCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFV-9cATsnyPa_oBk-5w7BmB7hm6Hk4aQ',
    appId: '1:691177676500:ios:aa30809251b86d9d7ba541',
    messagingSenderId: '691177676500',
    projectId: 'open-course-tech',
    storageBucket: 'open-course-tech.appspot.com',
    iosClientId: '691177676500-8bk8v02q7mqrfu9eqi2ekq2vrnlg1nk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.openCourse',
  );
}
